spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/blog?useUnicode=true&characterEncoding=utf-8&&useSSL=false&serverTimezone=UTC
    username: root
    password: uAiqwVwjJ8-i
#    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    root: warn
    com.readdown: info
  file: log/blog-pro.log

server:
  port: 8080


